# Generated by Django 5.0.1 on 2024-02-13 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_name_project_title_rename_name_status_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Creater',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='creater',
            new_name='user',
        ),
    ]
